Staging
wri/fw_api pull request #98
Opened 2022-10-24 09:09 UTC by edward3sc

Changes to satisfy support ticket [SP-1399](https://3sidedcube.atlassian.net/browse/SP-1399)

2022-11-07 15:10 UTC, correcthorsebatterystaple requested changes

2022-11-07 15:10 UTC, correcthorsebatterystaple commented on app/src/services/areas.service.js
> +      } else return [];
```suggestion
      }
      return [];
```

2022-11-07 15:10 UTC, correcthorsebatterystaple commented on app/src/services/areas.service.js
> +          if (area.attributes.admin && Object.keys(area.attributes.admin).length > 0) gadm = true;
```suggestion
          const wdpa = !!area.attributes.wdpaid;
          const gadm = !!area.attributes.admin && Object.keys(area.attributes.admin).length > 0;
```

2022-11-07 15:10 UTC, correcthorsebatterystaple commented on app/src/services/areas.service.js
> +          return !(wdpa || gadm);
```suggestion
          return !wdpa && !gadm;
```

2022-11-07 15:10 UTC, correcthorsebatterystaple commented on docker-compose-develop.yml
> +    image: mongo:3.6
Any breaking changed to worry about?

2022-11-07 16:03 UTC, edward3sc commented on docker-compose-develop.yml
> +    image: mongo:3.6
Nope

2022-11-08 10:31 UTC, wxllJK approved these changes

2022-11-08 10:41 UTC, owenjs approved these changes

2022-11-08 10:42 UTC, correcthorsebatterystaple approved these changes

2022-11-08 10:43 UTC, merged